name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -q   # donâ€™t ignore failures

  train_and_register:
    needs: test
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/mlops_open_source.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_EXPERIMENT: iris_experiment
      MLFLOW_MODEL_NAME: iris_model
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Generate dataset
        run: python src/make_dataset.py
      - name: Train model
        run: python src/train.py --n-estimators 100
      - name: Evaluate model
        run: python src/evaluate.py
      - name: Register best model (if meets threshold)
        run: python src/register_model.py --threshold 0.90

  build_and_push_docker:
    needs: train_and_register
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Docker image
        run: |
          docker buildx build . \
            -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/iris-api:latest \
            --push

  deploy_to_cloud_run:
    needs: build_and_push_docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy iris-api \
            --image=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/iris-api:latest \
            --platform=managed \
            --region=${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --memory=1Gi --cpu=1 \
            --set-env-vars=MLFLOW_TRACKING_URI=https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/mlops_open_source.mlflow,MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USERNAME }},MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }},MLFLOW_EXPERIMENT=iris_experiment,MLFLOW_MODEL_NAME=iris_model
